# This code is for node selector
# A node selector is the simplest way to control which node a Pod gets scheduled on in a 
# Kubernetes cluster. It uses labels on nodes to guide the scheduler.

apiVersion: v1
kind: Pod
metadata:
  name: node-selector-demo
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
  nodeSelector:
    disktype: ssd  # node labeld


